name: netcode_backend
description: Dart implementation of netcode backend
version: 0.0.0
repository: https://github.com/Hyla96/netcode/netcode_backend
topics: [netcode, gaming]

environment:
  sdk: ^3.5.0

dependencies:
  pointycastle: ^3.9.1
  netcode_core: ^0.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
