const int CHALLENGE_TOKEN_MAX_LENGTH = 300;
const int CHALLENGE_TOKEN_HMAC_LENGTH = 16;
const int CHALLENGE_TOKEN_NONCE_LENGTH = 12;

const int PRIVATE_TOKEN_MAX_LENGTH = 1024;
const int PRIVATE_TOKEN_HMAC_LENGTH = 16;
const int PRIVATE_TOKEN_NONCE_LENGTH = 24;

const int ENCRYPTED_TOKEN_MAC_LENGTH = 16;
