name: netcode_core
description: Core library for netcode implementation
version: 0.0.0
repository: https://github.com/Hyla96/netcode/netcode_core
topics: [netcode, gaming]

environment:
  sdk: ^3.5.0

dependencies:
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
